### ISSUE TITLE
Does s3-ghost support files as well as images?

### ISSUE THREAD

**Issue by iFloris** [tranvansang/s3-ghost#1]
Hello @tranvansang as you undoubtedly know, Ghost added support for files, video and audio. 
There are a number of s3-adapter for ghost, but at the moment they only support images.
Does your s3-ghost adapter support files as well as images? The comments at [line 40 and 41](https://github.com/tranvansang/s3-ghost/blob/a6ffa1d72c64afc2b514a3ccdcb28a0e746a0a8c/index.ts#L41) of [index.ts](https://github.com/tranvansang/s3-ghost/blob/master/index.ts) seem to indicate that images were supported in an older version, but line 42 only references `.getContentPath('images')`.

**Comment by tranvansang** [comment]
https://github.com/tranvansang/s3-ghost/commit/f345da3ef29e4833caca4041e181bd98245c943a

yes, previously I looked at the latest ghost to implement the feature.
However, my ghost deployment was old and didn't support other formats. The plugin broke. So I need to switch back to image support only.

I didn't have enough time to do the version check.

**Comment by iFloris** [comment]
Thanks, that is clear.
